version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - webnet
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - webnet
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - webnet
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webnet
  gateway:
    image: mgasfsu667/gateway
    ports:
      - "4000:4000"
    deploy:
      replicas: 1
    networks:
      - webnet
    environment:
      - FRONT_END_HOST_URL=http://frontend:3000
      - MESSANGER_HOST_URL=http://messanger:6000
      - AUTH_SERVICE_URL=http://authservice:6001
      - LISTING_SERVICE_URL=http://listingservice:6002
      - IMAGE_SERVICE_URL=http://imageservice:6003
      - WEBSOCKET_HOST=http://websocket:6500/websocket
  frontend:
    image: mgasfsu667/react-demo
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REACT_APP_WEBSOCKET_HOST=6500
  websocket:
    image: mgasfsu667/websocket-demo
    depends_on:
      - redis
    ports:
      - "6500:6500"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - WEBSOCKET_HOST=6500
  messanger:
    image: mgasfsu667/messanger-demo
    depends_on:
      - redis
      - mongodb
    ports:
      - "6000:6000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongodb:27017
      - MONGOCLIENT_DB=centStoreDB
      - MESSAGES_COLLECTION=messagesCollection
      - MESSANGER_HOST=6000
  imageservice:
    image: mgasfsu667/imageservice-demo
    depends_on:
      - redis
      - mongodb
    ports:
      - "6003:6003"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongodb:27017
  authservice:
    image: mgasfsu667/authservice-demo
    depends_on:
      - redis
      - mongodb
    ports:
      - "6001:6001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongodb:27017
      - MONGOCLIENT_DB=centStoreDB
      - USER_COLLECTION=userCollection
      - AUTH_SERVICE=6001
  jobworker:
    image: mgasfsu667/jobworker-demo
    depends_on:
      - redis
      - mongodb
    ports:
      - "6004:6004"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongodb:27017
  listingservice:
    image: mgasfsu667/listingservice-demo
    depends_on:
      - redis
      - mongodb
    ports:
      - "6002:6002"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb://mongodb:27017
      - MONGOCLIENT_DB=centStoreDB
      - LISTING_COLLECTION=listingCollection
      - LISTING_SERVICE=6002
networks:
  webnet: null
